### ISSUE TITLE
compiled error

### ISSUE THREAD

**Issue by tendence** [PkuRainBow/Hard-Aware-Deeply-Cascaed-Embedding#1]
Compiled in Ubuntu with error: ‘>>’ should be ‘> >’ within a nested template argument list.

It looks like some incompatible while compiled in Ubuntu.

Another error is the 

`for (auto const &ent1 : label_data_map)`

It can't be parsed.

**Comment by PkuRainBow** [comment]
@tendence 

(1) My code is compiled with Visual Studio 2013, the refered  ‘> >’  may be caused by different platform.

(2)the `for (auto const &ent1 : label_data_map)` is written in the style of C++11.  There should be no problem with this line.

**Comment by tendence** [comment]
@PkuRainBow 
It looks like only when I replaced all your C++11 feature code, can I compile it.

**Comment by tendence** [comment]
@PkuRainBow 
When run the script(has changed to shell), I encountered another problem.
`E0213 22:27:34.362665  3195 io.cpp:80] Could not open or find file /home/jack/Downloads/ppdownload/DeepFashion/consumer-to-shop/Img/img/TROUSERS/Pants/id_00017736/comsumer_01.jpg	17734
F0213 22:27:34.362689  3195 image_data_layer.cpp:72] Check failed: cv_img.data Could not load img/TROUSERS/Pants/id_00017736/comsumer_01.jpg	17734
`
It looks like my io.cpp is different from yours.
It can't seperate the tags from image paths?

**Comment by PkuRainBow** [comment]
@tendence  You could check the seperator is "\sp" or "\t". This is a small problem of caffe~ some versions only support "\sp"~

**Comment by tendence** [comment]
@PkuRainBow  Thank you for that.

Besides, is
`layer {
  bottom: "loss1/classifier"
  top: "loss1/classifier_norm"
  name: "loss1/l2_norm"
  type: "Normalization"
}`
also a specified layer? I found none in the updated BVLC/Caffe repo.

The error message is
`Unknown layer type: Normalization`

**Comment by PkuRainBow** [comment]
@tendence 
Yes, I will commit the L2-norm layer latter today ~

You could refer the implementation  [normalization_layer.cpp](https://github.com/freesouls/caffe/tree/master/src/caffe/layers ) firstly ~
